language: cpp
services:
  - docker
jobs:
  include:
    - env: docker_image=ubuntu:focal dist=focal arch=amd64
    - env: docker_image=ubuntu:bionic dist=bionic arch=amd64
    - env: docker_image=ubuntu:xenial dist=xenial arch=amd64
    - env: docker_image=debian:buster dist=buster arch=amd64
    - env: docker_image=debian:stretch dist=stretch arch=amd64
script:
  - |
    tools/build-deb-with-docker.sh \
      "${docker_image}" \
      "${dist}" "${arch}"

